### ISSUE TITLE
Current limiting drive

### ISSUE THREAD

**Issue by eskiles** [koibots8230/Anglerfish-2024#19]
https://github.com/koibots8230/Anglerfish-2024/blob/3a283ab3318b1505fdec74946a97fd34219b39a0/src/main/java/com/koibots/robot/Constants.java#L85

If I am reading this correctly, drive motors are capped at 60. Neos on drive can run at 80.

**Comment by JakeStew81** [comment]
There's a couple reasons we have it capped to 60A. One of which is that is the upper limit of what REV recommends [here](https://docs.revrobotics.com/sparkmax/gs-sm/connect-a-spark-max-over-usb). The bigger reason though is that we're already seeing massive dips in battery voltage throughout a match (on undercharged batteries we see brownouts as well), and pulling a combined 80A extra will only make the issue worse. 

If we had the time, I'd be all for testing this and seeing if it causes issues, but unfortunately we've only got two real work days between now and districts, and I don't think it's worth the risk trying it untested.
